# TABLES
CREATE_RELATIONSHIPS_TABLE = """
CREATE TABLE IF NOT EXISTS relationships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship TEXT NOT NULL UNIQUE
  );"""

CREATE_PEOPLE_TABLE = """
CREATE TABLE IF NOT EXISTS people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  relationship_id INTEGER NOT NULL,
  CONSTRAINT fk_relationship FOREIGN KEY (relationship_id) REFERENCES relationships(id)
  );"""
  
CREATE_PRAYERS_TABLE = """
CREATE TABLE IF NOT EXISTS prayers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id INTEGER NOT NULL,
  prayer TEXT NOT NULL,
  has_prayed BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE
  );"""

# INDEXES
CREATE_INDEX_ON_PEOPLE_RELATIONSHIP = """
CREATE INDEX IF NOT EXISTS idx_people_relationship ON people(relationship_id);"""

CREATE_INDEX_ON_PRAYERS_PERSON = """
CREATE INDEX IF NOT EXISTS idx_prayers_person ON prayers(person_id);"""

# SELECT QUERIES

# People
SELECT_ALL_PEOPLE_QUERY = """
SELECT p.id, p.name, r.relationship
FROM people AS p
JOIN relationships AS r ON p.relationship_id = r.id"""

SELECT_RELATIONSHIP_PEOPLE_QUERY = f"{SELECT_ALL_PEOPLE_QUERY} WHERE r.relationship = %s"

SELECT_PERSON_QUERY = "SELECT * FROM people WHERE id = %s"

# Prayers
SELECT_ALL_PRAYERS_QUERY = "SELECT * FROM prayers"

SELECT_ALL_PRAYERS_BY_PERSON_QUERY = "SELECT * FROM prayers WHERE person_id = %s"

SELECT_PRAYER_QUERY = "SELECT * FROM prayers WHERE id = %s"

SELECT_PRAYER_BY_PERSON_QUERY = "SELECT * FROM prayers WHERE id = %s AND person_id = %s"


# Relationship
SELECT_ALL_RELATIONSHIPS_QUERY = "SELECT * FROM relationships"

SELECT_RELATIONSHIP_QUERY = "SELECT id FROM relationships WHERE relationship = %s"

# INSERT QUERIES
INSERT_RELATIONSHIP_ROWS = """
INSERT INTO relationships (relationship) 
VALUES (%s)
ON CONFLICT (relationship) DO NOTHING
"""

INSERT_PERSON_QUERY = """
INSERT INTO people (name, relationship_id) 
VALUES (%s, %s)
RETURNING id
"""

INSERT_DEFAULT_PRAYER_QUERY = """
INSERT INTO prayers (person_id, prayer) 
VALUES (%s, %s)
RETURNING id
"""

INSERT_PRAYER_QUERY = """
INSERT INTO prayers (person_id, prayer, has_prayed) VALUES (%s, %s, %s)
RETURNING *
"""

# UPDATE Queries
UPDATE_PERSON_NAME_QUERY = """
UPDATE people
SET name = %s
WHERE id = %s
RETURNING *
"""
UPDATE_PERSON_RELATIONSHIP_QUERY = """
UPDATE people
SET relationship_id = %s
WHERE id = %s
RETURNING *
"""

UPDATE_PERSON_NAME_AND_RELATIONSHIP_QUERY = """
UPDATE people
SET name = %s, 
    relationship_id = %s
WHERE id = %s
RETURNING *
"""

UPDATE_PRAYER_TEXT_QUERY = """
UPDATE prayers
SET prayer = %s
WHERE id = %s
RETURNING *
"""

UPDATE_PRAYER_HAS_PRAYED_QUERY = """
UPDATE prayers
SET has_prayed = %s
WHERE id = %s
RETURNING *
"""

UPDATE_PRAYER_TEXT_AND_HAS_PRAYED_QUERY = """
UPDATE prayers
SET prayer = %s,
    has_prayed = %s
WHERE id = %s
RETURNING *
"""

# DELETE Queries
DELETE_PERSON_QUERY = """
DELETE FROM people 
WHERE id = %s
RETURNING *
"""

DELETE_PRAYER_QUERY = """
DELETE FROM prayers 
WHERE id = %s
RETURNING *
"""