# TABLES
CREATE_RELATIONSHIPS_TABLE = """
CREATE TABLE IF NOT EXISTS relationships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship TEXT NOT NULL UNIQUE
  );
"""

CREATE_AUTH_SCHEMA_FOR_TESTS = """
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
  id UUID PRIMARY KEY
);
"""

CREATE_PROFILES_TABLE = """
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY 
    REFERENCES auth.users(id) 
    ON DELETE CASCADE,
  display_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
  );"""

CREATE_PEOPLE_TABLE = """
CREATE TABLE IF NOT EXISTS people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  relationship_id INTEGER NOT NULL
    REFERENCES relationships(id),
  user_id UUID NOT NULL
    REFERENCES profiles(id)
    ON DELETE CASCADE
  );"""
  
CREATE_PRAYERS_TABLE = """
CREATE TABLE IF NOT EXISTS prayers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id INTEGER NOT NULL
    REFERENCES people(id) 
    ON DELETE CASCADE,
  prayer TEXT NOT NULL,
  has_prayed BOOLEAN NOT NULL DEFAULT FALSE
  );"""

# INDEXES
CREATE_INDEX_ON_PEOPLE_USER_ID = """
CREATE INDEX IF NOT EXISTS idx_people_user_id 
ON people(user_id);
"""

CREATE_INDEX_ON_PEOPLE_RELATIONSHIP = """
CREATE INDEX IF NOT EXISTS idx_people_relationship 
ON people(relationship_id);
"""

PEOPLE_USER_NORMALIZED_NAME_UNIQUE_INDEX = "uq_people_user_normalized_name"

CREATE_UNIQUE_INDEX_ON_PEOPLE_USER_NORMALIZED_NAME = f"""
CREATE UNIQUE INDEX IF NOT EXISTS {PEOPLE_USER_NORMALIZED_NAME_UNIQUE_INDEX}
ON people (user_id, lower(btrim(name)));
"""

CREATE_INDEX_ON_PRAYERS_PERSON = """
CREATE INDEX IF NOT EXISTS idx_prayers_person 
ON prayers(person_id);
"""

# SELECT QUERIES

# People
SELECT_ALL_PEOPLE_QUERY = """
SELECT p.id, p.name, r.relationship
FROM people AS p
JOIN relationships AS r ON p.relationship_id = r.id
WHERE p.user_id = %s
ORDER BY p.id ASC;
"""

SELECT_RELATIONSHIP_PEOPLE_QUERY = """
SELECT p.id, p.name, r.relationship
FROM people AS p
JOIN relationships AS r ON p.relationship_id = r.id
WHERE p.user_id = %s AND 
      r.relationship = %s
"""

SELECT_PERSON_QUERY = """
SELECT * 
FROM people as p
WHERE p.user_id = %s AND
      id = %s 
"""

# Prayers
SELECT_ALL_PRAYERS_QUERY = """
SELECT pr.*
FROM prayers AS pr
JOIN people as p ON pr.person_id = p.id
WHERE p.user_id = %s
ORDER BY pr.id ASC;
"""

SELECT_ALL_PRAYERS_BY_PERSON_QUERY = """
SELECT pr.* 
FROM prayers AS pr
JOIN people AS p ON pr.person_id = p.id 
WHERE p.user_id = %s AND
      pr.person_id = %s
ORDER BY pr.id ASC;
"""

SELECT_PRAYER_QUERY = """
SELECT * 
FROM prayers 
WHERE id = %s
"""

SELECT_PRAYER_BY_PERSON_QUERY = """
SELECT * 
FROM prayers 
WHERE id = %s AND 
      person_id = %s
"""


# Relationship
SELECT_ALL_RELATIONSHIPS_QUERY = """
SELECT *
FROM relationships
"""

SELECT_RELATIONSHIP_QUERY = """
SELECT id 
FROM relationships 
WHERE relationship = %s    
"""


# INSERT QUERIES
INSERT_RELATIONSHIP_ROWS = """
INSERT INTO relationships (relationship) 
VALUES (%s)
ON CONFLICT (relationship) DO NOTHING
"""

INSERT_PERSON_QUERY = """
INSERT INTO people (name, relationship_id, user_id) 
VALUES (%s, %s, %s)
RETURNING id
"""

INSERT_DEFAULT_PRAYER_QUERY = """
INSERT INTO prayers (person_id, prayer) 
VALUES (%s, %s)
RETURNING id
"""

INSERT_PRAYER_QUERY = """
INSERT INTO prayers (person_id, prayer, has_prayed)
VALUES (%s, %s, %s)
RETURNING *
"""


# UPDATE Queries
UPDATE_PERSON_NAME_QUERY = """
UPDATE people
SET name = %s
WHERE user_id = %s AND 
      id = %s
RETURNING *
"""

UPDATE_PERSON_RELATIONSHIP_QUERY = """
UPDATE people
SET relationship_id = %s
WHERE user_id = %s AND
      id = %s 
RETURNING *
"""

UPDATE_PERSON_NAME_AND_RELATIONSHIP_QUERY = """
UPDATE people
SET name = %s, 
    relationship_id = %s
WHERE user_id = %s AND
      id = %s
RETURNING *
"""

UPDATE_PRAYER_TEXT_QUERY = """
UPDATE prayers AS pr
SET prayer = %s
FROM people AS p
WHERE pr.person_id = p.id AND
      p.user_id = %s AND
      pr.person_id = %s AND
      pr.id = %s
RETURNING pr.*
"""

UPDATE_PRAYER_HAS_PRAYED_QUERY = """
UPDATE prayers AS pr
SET has_prayed = %s
FROM people AS p
WHERE pr.person_id = p.id AND
      p.user_id = %s AND
      pr.person_id = %s AND
      pr.id = %s
RETURNING pr.*
"""

UPDATE_PRAYER_TEXT_AND_HAS_PRAYED_QUERY = """
UPDATE prayers AS pr
SET prayer = %s,
    has_prayed = %s
FROM people AS p
WHERE pr.person_id = p.id AND
      p.user_id = %s AND
      pr.person_id = %s AND
      pr.id = %s
RETURNING pr.*
"""

# DELETE Queries
DELETE_PERSON_QUERY = """
DELETE FROM people
WHERE user_id = %s AND
      id = %s
RETURNING *
"""

DELETE_PRAYER_QUERY = """
DELETE FROM prayers AS pr 
USING people AS p
WHERE pr.person_id = p.id AND
      p.user_id = %s AND
      pr.person_id = %s AND
      pr.id = %s
RETURNING pr.*
"""
