name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    steps:
      - name: Trigger Render deploy
        run: curl "$deploy_url"



